services:
  - type: web
    name: clinic-health
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn clinic.wsgi:application --workers 1 --threads 10
